### ISSUE TITLE
2x2x2 simulator Single-Step on mobile

### ISSUE THREAD

**Issue by bcube2** [mjstraughan/CubingHistory#5]
Hi,

on mobile, when pressing the Single-Step-forward button in the 2x2 Methods section, the simulator is playing 2 moves instead of 1.

**Comment by mjstraughan** [comment]
I will have to open this as an issue on the AnimCubeJS GitHub.

**Comment by bcube2** [comment]
Well, clearly, the issue has nothing to do with the AnimCubeJS itself. I believe it is a consequence of setting the simulator up on your page.

Maybe Eric could help?

**Comment by mjstraughan** [comment]
Consider that maybe it isn't so clear to a non-programmer such as myself. Who knows, maybe the non-programmer thinks that maybe AnimCubeJS is designed to work and be used with various platforms, such as Docusaurus, and that there could be some kind of bug with AnimCubeJS causing issues. Or maybe they think that Docusaurus is designed to be compatible with various features or standards of other programs and that AnimCubeJS needs a slight update to be compatible. Or maybe they think of other possibilities. It is very easy for the non-programmer to think that AnimCubeJS would be fully compatible with Docusaurus since it works on numerous other websites. The point is that something technical such as this isn't clear to someone who knows little about it.

I hate to keep bothering Eric about fixes, but it seems to be the best direction. He is very helpful.

**Comment by bcube2** [comment]
It is working correctly as of now.
